export const GENRES = [
    { id: 28, name: "Action" },
    { id: 12, name: "Adventure" },
    { id: 16, name: "Animation" },
    { id: 35, name: "Comedy" },
    { id: 80, name: "Crime" },
    { id: 99, name: "Documentary" },
    { id: 18, name: "Drama" },
    { id: 10751, name: "Family" },
    { id: 14, name: "Fantasy" },
    { id: 36, name: "History" },
    { id: 27, name: "Horror" },
    { id: 10402, name: "Music" },
    { id: 9648, name: "Mystery" },
    { id: 10749, name: "Romance" },
    { id: 878, name: "Science Fiction" },
    { id: 53, name: "Thriller" },
    { id: 10752, name: "War" },
    { id: 37, name: "Western" },
];
export const LANGUAGES = [
    { code: "te", name: "Telugu" },
    { code: "hi", name: "Hindi" },
    { code: "ta", name: "Tamil" },
    { code: "ml", name: "Malayalam" },
    { code: "kn", name: "Kannada" },
    { code: "en", name: "English" },
    { code: "ko", name: "Korean" },
    { code: "ja", name: "Japanese" },
    { code: "es", name: "Spanish" },
    { code: "fr", name: "French" },
];
export const SAMPLE_MOVIES = [
    {
        id: 1,
        title: "Ye Maaya Chesave",
        overview: "A young man falls in love with his neighbor, a Christian girl, and the story follows their complicated love story across different phases of their lives.",
        poster_path: "https://image.tmdb.org/t/p/w500/ye-maaya-chesave.jpg",
        backdrop_path: "",
        release_date: "2010-02-26",
        vote_average: 7.8,
        vote_count: 1200,
        genre_ids: [18, 10749],
        original_language: "te",
        popularity: 85.5,
    },
    {
        id: 2,
        title: "Shiva",
        overview: "A college student takes on local goons terrorizing his campus. A landmark action drama that redefined Telugu cinema.",
        poster_path: "https://image.tmdb.org/t/p/w500/shiva.jpg",
        backdrop_path: "",
        release_date: "1989-10-06",
        vote_average: 8.2,
        vote_count: 3400,
        genre_ids: [28, 18],
        original_language: "te",
        popularity: 92.3,
    },
    {
        id: 3,
        title: "Baahubali: The Beginning",
        overview: "In ancient India, an adventurous and daring man discovers his royal heritage and must reclaim his kingdom.",
        poster_path: "https://image.tmdb.org/t/p/w500/baahubali.jpg",
        backdrop_path: "",
        release_date: "2015-07-10",
        vote_average: 8.0,
        vote_count: 5600,
        genre_ids: [28, 18, 14],
        original_language: "te",
        popularity: 120.7,
    },
    {
        id: 4,
        title: "Arjun Reddy",
        overview: "A brilliant but temperamental surgeon lets his personal life spiral out of control when his girlfriend is forced to marry another man.",
        poster_path: "https://image.tmdb.org/t/p/w500/arjun-reddy.jpg",
        backdrop_path: "",
        release_date: "2017-08-25",
        vote_average: 7.9,
        vote_count: 4200,
        genre_ids: [18, 10749],
        original_language: "te",
        popularity: 110.2,
    },
    {
        id: 5,
        title: "RRR",
        overview: "A fictional tale of two legendary revolutionaries and their journey away from home before they began fighting for their country.",
        poster_path: "https://image.tmdb.org/t/p/w500/rrr.jpg",
        backdrop_path: "",
        release_date: "2022-03-25",
        vote_average: 8.1,
        vote_count: 8900,
        genre_ids: [28, 18, 36],
        original_language: "te",
        popularity: 150.3,
    },
    {
        id: 6,
        title: "Eega",
        overview: "A murdered man reincarnates as a housefly to take revenge on his killer and protect the woman he loves.",
        poster_path: "https://image.tmdb.org/t/p/w500/eega.jpg",
        backdrop_path: "",
        release_date: "2012-07-06",
        vote_average: 7.5,
        vote_count: 2100,
        genre_ids: [14, 35, 18],
        original_language: "te",
        popularity: 78.4,
    },
    {
        id: 7,
        title: "Ala Vaikunthapurramuloo",
        overview: "Bantu grows up hated by his father. When he discovers that he was switched at birth, he tries to enter the house of his biological father.",
        poster_path: "https://image.tmdb.org/t/p/w500/ala-vaikunthapurramuloo.jpg",
        backdrop_path: "",
        release_date: "2020-01-12",
        vote_average: 7.3,
        vote_count: 3100,
        genre_ids: [28, 35, 18],
        original_language: "te",
        popularity: 95.6,
    },
    {
        id: 8,
        title: "Pellichoopulu",
        overview: "Two young people, pressured into an arranged marriage, hatch a plan to start a food truck business together.",
        poster_path: "https://image.tmdb.org/t/p/w500/pellichoopulu.jpg",
        backdrop_path: "",
        release_date: "2016-07-22",
        vote_average: 7.7,
        vote_count: 1800,
        genre_ids: [35, 18, 10749],
        original_language: "te",
        popularity: 72.1,
    },
    {
        id: 9,
        title: "C/o Kancharapalem",
        overview: "Four love stories set in the Kancharapalem area of Visakhapatnam, exploring love across age, class, and religion.",
        poster_path: "https://image.tmdb.org/t/p/w500/kancharapalem.jpg",
        backdrop_path: "",
        release_date: "2018-09-07",
        vote_average: 8.3,
        vote_count: 1500,
        genre_ids: [18, 10749],
        original_language: "te",
        popularity: 65.8,
    },
    {
        id: 10,
        title: "Jersey",
        overview: "A failed cricketer decides to return to cricket in his mid-30s, driven by his son's wish for a jersey as a gift.",
        poster_path: "https://image.tmdb.org/t/p/w500/jersey.jpg",
        backdrop_path: "",
        release_date: "2019-04-19",
        vote_average: 8.4,
        vote_count: 2800,
        genre_ids: [18, 10751],
        original_language: "te",
        popularity: 88.9,
    },
    {
        id: 11,
        title: "Parasite",
        overview: "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.",
        poster_path: "https://image.tmdb.org/t/p/w500/parasite.jpg",
        backdrop_path: "",
        release_date: "2019-05-30",
        vote_average: 8.6,
        vote_count: 15000,
        genre_ids: [53, 35, 18],
        original_language: "ko",
        popularity: 180.2,
    },
    {
        id: 12,
        title: "The Shawshank Redemption",
        overview: "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
        poster_path: "https://image.tmdb.org/t/p/w500/shawshank.jpg",
        backdrop_path: "",
        release_date: "1994-09-23",
        vote_average: 9.3,
        vote_count: 24000,
        genre_ids: [18, 80],
        original_language: "en",
        popularity: 200.5,
    },
];
export const MOVIE_FACTS = [
    {
        title: "24 Crafts of Cinema",
        description: "From screenplay to sound design, cinema involves 24 distinct crafts working in harmony to create the magic we see on screen.",
        icon: "🎬",
    },
    {
        title: "Your Brain on Movies",
        description: "Watching movies activates mirror neurons, making you feel emotions as if you're experiencing them yourself. Cinema literally changes brain chemistry.",
        icon: "🧠",
    },
    {
        title: "The First Telugu Film",
        description: "Bhakta Prahlada (1931) was the first Telugu talkie film, marking the beginning of a rich cinematic tradition spanning over 90 years.",
        icon: "🎞️",
    },
    {
        title: "Frame by Frame",
        description: "A typical movie runs at 24 frames per second. A 2-hour film contains over 172,800 individual frames, each carefully crafted.",
        icon: "🖼️",
    },
    {
        title: "The Power of Sound",
        description: "70% of emotional impact in cinema comes from the soundtrack. Music directors like AR Rahman transform scenes into unforgettable experiences.",
        icon: "🎵",
    },
    {
        title: "Light is Everything",
        description: "Cinematography — the art of painting with light — can make the same scene feel joyful or terrifying. It's the soul of visual storytelling.",
        icon: "💡",
    },
];
export const CRAFTS_OF_CINEMA = [
    "Direction", "Screenplay", "Cinematography", "Editing", "Music Direction",
    "Sound Design", "Art Direction", "Costume Design", "Makeup", "Choreography",
    "Stunts", "VFX", "DI & Color Grading", "Production Design", "Dialogue Writing",
    "Lyrics", "Background Score", "Dubbing", "Foley Art", "Title Design",
    "Casting", "Line Production", "Still Photography", "Publicity Design",
];
